version: "3"

services:
  back:
    image: vmonomakhoff/tp2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    expose:
      - "8080:8080"  
    environment : 
     - ENVIRONMENT=back
     
  front:
     image: vmonomakhoff/tp2_f
     deploy:
       replicas: 5
       resources:
         limits:
           cpus: "0.1"
           memory: 50M
       restart_policy:
         condition: on-failure
     ports:
       - "8081:8081"
     environment : 
       - APP_PORT=8081 
       - WS_BACK_URL=172.17.0.1

